before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn deploy javadoc:jar source:jar gpg:sign --settings target/travis/settings.xml"
language: java
install: true
matrix:
  include:
  - jdk: openjdk7
